In [1]:
import sys
import collections
import dpkt
import socket
import os
import random
import math
import numpy as np
from scipy.stats import kurtosis, skew
from termcolor import colored
from joblib import Parallel, delayed

# Extract UDP DATA

# Extract TCP DATA

In [2]:
import processing_TCP
data_folder = "/Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/action_data"
DEST_IP = '192.168.1.1'
SOURCE_IP = '192.168.1.10'
all_actions = [d for d in os.listdir(data_folder) if os.path.isdir(os.path.join(data_folder, d))]
for action in all_actions:
    processing_TCP.FeatureExtractionCombined(data_folder, DEST_IP, SOURCE_IP, action)
    
    
    
#todo: clear output

155: 1
160: 0
165: 0
170: 2
155: 1
160: 0
165: 0
170: 3
155: 0
160: 0
165: 0
170: 4
155: 1
160: 0
165: 0
170: 3
155: 1
160: 0
165: 0
170: 3
155: 0
160: 0
165: 1
170: 3
155: 1
160: 0
165: 0
170: 3


/Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/processing_TCP.py:337: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  out_kurtosisBurst = kurtosis(out_bursts_packets)
/Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/processing_TCP.py:338: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  out_skewBurst = skew(out_bursts_packets)


155: 1
160: 0
165: 0
170: 2
155: 1
160: 0
165: 0
170: 3
155: 1
160: 0
165: 0
170: 3
155: 1
160: 0
165: 0
170: 3
155: 1
160: 0
165: 0
170: 3
155: 0
160: 0
165: 0
170: 4
155: 1
160: 0
165: 0
170: 3
155: 1
160: 0
165: 0
170: 3
155: 1
160: 0
165: 0
170: 3
155: 0
160: 1
165: 0
170: 3
155: 1
160: 0
165: 0
170: 3
155: 1
160: 0
165: 0
170: 2
155: 0
160: 0
165: 1
170: 2
155: 0
160: 0
165: 1
170: 3
155: 0
160: 0
165: 1
170: 3
155: 0
160: 0
165: 0
170: 3
155: 1
160: 0
165: 0
170: 2
155: 1
160: 0
165: 0
170: 3
155: 1
160: 1
165: 0
170: 2
155: 1
160: 1
165: 0
170: 2
155: 1
160: 1
165: 0
170: 1
155: 1
160: 1
165: 0
170: 1
155: 1
160: 1
165: 0
170: 2
155: 1
160: 1
165: 0
170: 2
155: 1
160: 1
165: 0
170: 1
155: 1
160: 1
165: 0
170: 4
155: 0
160: 2
165: 0
170: 5
155: 0
160: 2
165: 0
170: 5
155: 1
160: 1
165: 0
170: 4
155: 1
160: 1
165: 0
170: 1
155: 1
160: 1
165: 0
170: 3
155: 1
160: 1
165: 0
170: 4
155: 0
160: 2
165: 0
170: 2
155: 0
160: 2
165: 0
170: 4
155: 0
160: 2
165: 0
170: 1
155: 0
160: 2
165: 0

# EXTRACT TEMPORAL DEPENDENCIES

In [1]:
import os
import numpy as np
import pandas as pd
import temp_dep_extractor

data_folder = 'action_data'

# Get a list of all directories in the data_folder
all_actions = [d for d in os.listdir(data_folder) if os.path.isdir(os.path.join(data_folder, d))]

## EXTRACT CONVILUTION STATISTICS

In [2]:
kernel = np.array([154, 52, 90, 81, 52, 81, 725, 52, 81, 90, 157, 81, 154])

for action_name in all_actions:
    extraction_dir = os.path.join('extractedFeatures', action_name, 'conv')
    if not os.path.exists(extraction_dir):
        os.makedirs(extraction_dir)

    dir_path = os.path.join(data_folder, action_name)
    files = os.listdir(dir_path)
    
    for file in files:
        if (".DS_Store" in file):
            continue
        
        pcap_file_path = os.path.join(dir_path, file)
        timestamps, packet_sizes = temp_dep_extractor.parse_pcap(pcap_file_path)
        statistics = temp_dep_extractor.extract_conv_features(timestamps, packet_sizes, file[:-5], action_name, kernel)
        df = pd.DataFrame(statistics, index=[0])
        
        output_file_path = os.path.join(extraction_dir, f'{os.path.splitext(file)[0]}.csv')
        df.to_csv(output_file_path, index=False)

/Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/temp_dep_extractor.py:41: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure(figsize=(10,6))


## EXTRACT CORRELATION COEFFICIENT STATISTICS

In [3]:
data_folder = 'action_data'
kernel = np.array([104, 111, 104, 111, 104, 111])

for action_name in all_actions:
    extraction_dir = os.path.join('extractedFeatures', action_name, 'corr_coeff')
    if not os.path.exists(extraction_dir):
        os.makedirs(extraction_dir)

    dir_path = os.path.join(data_folder, action_name)
    files = os.listdir(dir_path)
    
    for file in files:
        if (".DS_Store" in file):
            continue
        pcap_file_path = os.path.join(dir_path, file)
        timestamps, packet_sizes = temp_dep_extractor.parse_pcap(pcap_file_path)

        # Extract features
        statistics = temp_dep_extractor.extract_corr_coeff_features(timestamps, packet_sizes, file[:-5], action_name, kernel)
        df = pd.DataFrame(statistics, index=[0])
        
        output_file_path = os.path.join(extraction_dir, f'{os.path.splitext(file)[0]}.csv')
        df.to_csv(output_file_path, index=False)


capTurnOnTap16.pcap
{'corr_mean': -0.0028852722706336604, 'corr_std': 0.5248788745113552, 'corr_median': 0.0, 'corr_percentile_25': -3.316095637543883e-17, 'corr_percentile_75': 3.316095637543883e-17, 'corr_max': 1.0, 'corr_min': -1.0, 'corr_skewness': 0.011525963508241392, 'corr_kurtosis': 0.36205660228588954, 'num_clusters': 1, 'total_length': 2.450531005859375, 'average_length': 2.450531005859375, 'total_time': 2.450531005859375, 'average_time_gap': 0}
capTurnOnTap5.pcap
{'corr_mean': -0.0011134019817543455, 'corr_std': 0.31745433286171143, 'corr_median': 0.0, 'corr_percentile_25': -3.1500705165500864e-17, 'corr_percentile_75': 3.1500705165500864e-17, 'corr_max': 1.0, 'corr_min': -1.0, 'corr_skewness': 0.0163296321837344, 'corr_kurtosis': 4.424060625610762, 'num_clusters': 1, 'total_length': 0.5196070671081543, 'average_length': 0.5196070671081543, 'total_time': 0.5196070671081543, 'average_time_gap': 0}
capTurnOnTap20.pcap
{'corr_mean': -0.0006969819940821571, 'corr_std': 0.1967504

/Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/temp_dep_extractor.py:113: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure(figsize=(10,6))


{'corr_mean': -0.0014859099175250918, 'corr_std': 0.21630442088922183, 'corr_median': 0.0, 'corr_percentile_25': 0.0, 'corr_percentile_75': 0.0, 'corr_max': 0.940217768679347, 'corr_min': -0.940217768679347, 'corr_skewness': 0.017063502495216397, 'corr_kurtosis': 6.86400670116652, 'num_clusters': 0, 'total_length': 0, 'average_length': 0, 'total_time': 0, 'average_time_gap': 0}
capTurnOnTap23.pcap
{'corr_mean': -0.0017358021877411734, 'corr_std': 0.20711436480044917, 'corr_median': 0.0, 'corr_percentile_25': -3.033359507987655e-17, 'corr_percentile_75': 4.5500392619814835e-17, 'corr_max': 0.9402177686793471, 'corr_min': -0.9402177686793471, 'corr_skewness': -0.017441379684345705, 'corr_kurtosis': 7.394335799589774, 'num_clusters': 0, 'total_length': 0, 'average_length': 0, 'total_time': 0, 'average_time_gap': 0}
capTurnOnTap19.pcap
{'corr_mean': -0.001622092943457076, 'corr_std': 0.17964324636872572, 'corr_median': 0.0, 'corr_percentile_25': -2.922030585236557e-17, 'corr_percentile_75'

{'corr_mean': -0.0007523557971768547, 'corr_std': 0.4339612679413215, 'corr_median': 0.0, 'corr_percentile_25': 0.0, 'corr_percentile_75': 0.0, 'corr_max': 0.9999999999999999, 'corr_min': -0.9999999999999999, 'corr_skewness': 0.0056394463629763835, 'corr_kurtosis': 1.666302553514524, 'num_clusters': 1, 'total_length': 2.1753129959106445, 'average_length': 2.1753129959106445, 'total_time': 2.1753129959106445, 'average_time_gap': 0}
capPickPlace1.pcap
{'corr_mean': 8.038753011521349e-05, 'corr_std': 0.4903625486028242, 'corr_median': -3.517247599984548e-17, 'corr_percentile_25': -3.517247599984549e-17, 'corr_percentile_75': 0.0, 'corr_max': 1.0, 'corr_min': -1.0, 'corr_skewness': 0.003003186854706715, 'corr_kurtosis': 0.7933400942254485, 'num_clusters': 2, 'total_length': 2.177698850631714, 'average_length': 1.088849425315857, 'total_time': 7.32662296295166, 'average_time_gap': 5.148924112319946}
capPickPlace15.pcap
{'corr_mean': -0.0013991533163848473, 'corr_std': 0.3920392155339531, 'c

{'corr_mean': -0.00041453406801136134, 'corr_std': 0.18063992786713223, 'corr_median': 0.0, 'corr_percentile_25': 0.0, 'corr_percentile_75': 5.3582509678464176e-17, 'corr_max': 0.9856222548132666, 'corr_min': -0.9828721869343219, 'corr_skewness': 0.08896142075292415, 'corr_kurtosis': 11.08134660763359, 'num_clusters': 0, 'total_length': 0, 'average_length': 0, 'total_time': 0, 'average_time_gap': 0}
capPourWater10.pcap
{'corr_mean': -0.0005109306412806992, 'corr_std': 0.42087781308441463, 'corr_median': -3.890697548273838e-17, 'corr_percentile_25': -3.890697548273838e-17, 'corr_percentile_75': 0.0, 'corr_max': 1.0, 'corr_min': -1.0, 'corr_skewness': 0.005448290526115614, 'corr_kurtosis': 2.1345205521027646, 'num_clusters': 1, 'total_length': 2.150174140930176, 'average_length': 2.150174140930176, 'total_time': 2.150174140930176, 'average_time_gap': 0}
capPourWater1.pcap
{'corr_mean': -0.0013745281215089447, 'corr_std': 0.17989806777797668, 'corr_median': 0.0, 'corr_percentile_25': -3.5

{'corr_mean': -0.00020915834255952033, 'corr_std': 0.4360009125483444, 'corr_median': 3.82811564215025e-17, 'corr_percentile_25': 0.0, 'corr_percentile_75': 3.8281156421502506e-17, 'corr_max': 0.9999999999999997, 'corr_min': -0.9999999999999997, 'corr_skewness': 0.006044679632137095, 'corr_kurtosis': 1.8492412434946335, 'num_clusters': 2, 'total_length': 2.2510159015655518, 'average_length': 1.1255079507827759, 'total_time': 42.531221866607666, 'average_time_gap': 40.280205965042114}
capPressKey7.pcap
{'corr_mean': -0.003909466516988144, 'corr_std': 0.2149595074551802, 'corr_median': 0.0, 'corr_percentile_25': -4.84280611486076e-17, 'corr_percentile_75': 0.0, 'corr_max': 0.963366101718176, 'corr_min': -0.9459459459459458, 'corr_skewness': -0.09961482219677162, 'corr_kurtosis': 6.000365922288722, 'num_clusters': 0, 'total_length': 0, 'average_length': 0, 'total_time': 0, 'average_time_gap': 0}
capPressKey11.pcap
{'corr_mean': -0.00014832672130820826, 'corr_std': 0.6964886770289807, 'cor

{'corr_mean': -0.0028028017301375383, 'corr_std': 0.283576874426993, 'corr_median': 0.0, 'corr_percentile_25': 0.0, 'corr_percentile_75': 0.0, 'corr_max': 0.9999999999999998, 'corr_min': -1.0, 'corr_skewness': 0.0045813519480108495, 'corr_kurtosis': 4.273475100799929, 'num_clusters': 0, 'total_length': 0, 'average_length': 0, 'total_time': 0, 'average_time_gap': 0}
capPressKey9.pcap
{'corr_mean': -0.0007742725821580312, 'corr_std': 0.6955519566017819, 'corr_median': 0.0, 'corr_percentile_25': -0.4710562351721581, 'corr_percentile_75': 0.49841579692241894, 'corr_max': 0.9999999999999999, 'corr_min': -0.9999999999999999, 'corr_skewness': 0.005637658582700652, 'corr_kurtosis': -1.0122997238208955, 'num_clusters': 1, 'total_length': 5.996596813201904, 'average_length': 5.996596813201904, 'total_time': 5.996596813201904, 'average_time_gap': 0}
capPressKey13.pcap
{'corr_mean': -0.00027229842630138365, 'corr_std': 0.5733337244986535, 'corr_median': 3.320238530684308e-17, 'corr_percentile_25':

# TRAIN CLASSIFIER

In [4]:
import traffic_classifier
import warnings
import pandas as pd


directory_path = '/Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures'  # specify the directory where your CSV files are located
traffic_classifier.mergeDatasets(directory_path)
file_path = '/Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/all_classes.csv'
x, y, feature_id = traffic_classifier.preprocess(file_path)
warnings.filterwarnings(action='ignore', category=DeprecationWarning)
file_path = '/Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/all_classes.csv'
# Load the CSV file into a DataFrame
df = pd.read_csv(file_path)

# Get the feature names
feature_names = df.columns.tolist()

tpr, fpr, auc = traffic_classifier.runClassificationKFold_CV(file_path, feature_names)

Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/turnOnTap/pkt_len/capTurnOnTap19.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/turnOnTap/pkt_len/capTurnOnTap25.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/turnOnTap/pkt_len/capTurnOnTap24.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/turnOnTap/pkt_len/capTurnOnTap18.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/turnOnTap/pkt_len/capTurnOnTap20.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/turnOnTap/pkt_len/capTurnOnTap21.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cyberse

Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/turnOnTap/conv/capTurnOnTap2.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/turnOnTap/conv/capTurnOnTap3.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/turnOnTap/conv/capTurnOnTap1.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/turnOnTap/conv/capTurnOnTap8.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/turnOnTap/conv/capTurnOnTap9.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/turnOnTap/conv/capTurnOnTap13.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extract

Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/pickPlace/pkt_len/capPickPlace13.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/pickPlace/pkt_len/capPickPlace17.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/pickPlace/pkt_len/capPickPlace16.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/pickPlace/pkt_len/capPickPlace14.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/pickPlace/pkt_len/capPickPlace15.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/pickPlace/conv_features/capPickPlace18.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/c

Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/pickPlace/traff_stats/capPickPlace8.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/pickPlace/traff_stats/capPickPlace9.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/pickPlace/traff_stats/capPickPlace7.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/pickPlace/traff_stats/capPickPlace6.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/pickPlace/traff_stats/capPickPlace4.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/pickPlace/traff_stats/capPickPlace5.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple

Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/pourWater/traff_stats/capPourWater24.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/pourWater/traff_stats/capPourWater18.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/presskey/pkt_len/capPressKey12.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/presskey/pkt_len/capPressKey13.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/presskey/pkt_len/capPressKey11.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/presskey/pkt_len/capPressKey10.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cyberse

Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/presskey/conv/capPressKey23.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/presskey/traff_stats/capPressKey12.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/presskey/traff_stats/capPressKey13.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/presskey/traff_stats/capPressKey11.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/presskey/traff_stats/capPressKey10.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/extractedFeatures/presskey/traff_stats/capPressKey14.csv
Attempting to read: /Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cy

Confusion Matrix: 
[[3 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 1 1]]
Confusion Matrix: 
[[3 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 0 2]]
Confusion Matrix: 
[[3 0 0 0]
 [0 3 0 0]
 [0 0 1 1]
 [0 0 0 2]]
Confusion Matrix: 
[[3 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [1 0 0 1]]
Confusion Matrix: 
[[3 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 3]]
Confusion Matrix: 
[[2 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 3]]
Confusion Matrix: 
[[2 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 3]]
Confusion Matrix: 
[[2 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 3]]
Confusion Matrix: 
[[2 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 3]]
Confusion Matrix: 
[[2 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 0 2]]
Model AUC: 0.995
10-Fold AUC: 0.995
Mean Precision: 0.970
Mean Recall: 0.970
Mean F1 Score: 0.970
['corr_max', 0.3302883]
['packetLengthBin2_33', 0.11214434]
['packetLengthBin2_32', 0.10879165]
['packetLengthBin_19', 0.097732596]
['p60PacketTimesOut', 0.048271395]
['meanPacketTimes', 0.04203351]
['stdevPacketTimes', 0.03946352]
['packetLengthBin2_31', 0.0350

/Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/traffic_classifier.py:364: UserWarning: color is redundantly defined by the 'color' keyword argument and the fmt string "k--" (-> color='k'). The keyword argument will take precedence.
  ax1.plot([0, 1], [0, 1], 'k--', lw=2, color='orange', label = 'Random Guess')
/Users/ct/Library/Mobile Documents/com~apple~CloudDocs/cybersecurity_robotics/traffic_classifier.py:374: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
